SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_INS AS INS
JOIN ANIMAL_OUTS AS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE 1=1
    AND INS.SEX_UPON_INTAKE LIKE "%Intact%"
    AND (OUTS.SEX_UPON_OUTCOME LIKE "%Spayed%" OR
         OUTS.SEX_UPON_OUTCOME LIKE "%Neutered%")
