SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK_SALES.SALES*BOOK.PRICE) AS TOTAL_SALES
FROM BOOK INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
INNER JOIN BOOK_SALES ON BOOK.BOOK_ID=BOOK_SALES.BOOK_ID
WHERE YEAR(BOOK_SALES.SALES_DATE) = 2022 AND MONTH(BOOK_SALES.SALES_DATE) = 1
GROUP BY AUTHOR_ID,CATEGORY,AUTHOR_NAME
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC